backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "match"
    label: "Match"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Match Date", name: "date", widget: "datetime"}
      - {label: "title", name: "title", widget: "string", default: ""}
      - {label: "subtitle", name: "subtitle", widget: "string", default: "From 11:00 to 13:00"}
      - {label: "Location", name: "location", widget: "string", default: "Britannia"}
      - {label: "Match Duration", name: "duration", widget: "number", default: "2"}
      - {label: "Price", name: "price", widget: "number", default: "40"}
      - {label: "Monzo User", name: "monzouser", widget: "string", default: ""}
      - {label: Image, name: image, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
